### ISSUE TITLE
Native implementation

### ISSUE THREAD

**Issue by maliayas** [tarwich/SelectByRegex#1]
How is this different than selecting a text and pressing <kbd>Alt</kbd> <kbd>F3</kbd>? Or doing a regex search and pressing "find all" button.

**Comment by tarwich** [comment]
I'm not at my computer at the moment to try your suggestion, but I tried to
create multiple selections with the native find and has a few problems:
- I don't use the mouse and there is no hot key for restricting results to
  "in selection"
- I was unable to reliably create multiple selections from the results of
  the native system
- My solution is one key vs several options that are toggles so you have to
  read them

Also my plugin uses the native find underneath so that things will be as
close to the original as possible.

Personally I would prefer to stay native and not have a plugin but I
haven't found a way yet.

**Comment by maliayas** [comment]
OK, I understand.
